### ISSUE TITLE
Institutions: HCR

### ISSUE THREAD

**Issue by mathisonclore** [rochelleterman/uprs#12]
**Rochelle text**
I added HCR but this should only refer to specific mentions of the UPR and HRC, not vague "recommendations"?

**current keywords**
![image](https://cloud.githubusercontent.com/assets/12419360/8851885/0a44d4ea-3120-11e5-9b91-ccdf62b1c184.png)

**Suggestion**
Change keywords?

**Comment by rochelleterman** [comment]
This was a miscommunication / typo: The keywords you listed there are under "UNHCR". "HRC" stands for "Human Rights Committee."

**Comment by mathisonclore** [comment]
Okay. So you were referring to the merged CCPR/old-HRC keywords (below) ? 

![image](https://cloud.githubusercontent.com/assets/12419360/8876612/c2cf2122-31ee-11e5-80e6-c8acd21e43d2.png)

**Comment by rochelleterman** [comment]
Yep -- what I did was add 'human rights committee' to CCPR, and then applied the "HRC" key to "Human Rights Council."  Reopen if this doesn't make sense!
