### ISSUE TITLE
Linkages: IMCW as migrants but not labor

### ISSUE THREAD

**Issue by mathisonclore** [rochelleterman/uprs#15]
**Rochelle text**
Erin is not classifying ICMW as "labor" but it has the word "migrants" in it. We need to highlight this in the codebook.

**Matt's action**
I added a linkage for labor with IMCW (though it wouldn't hurt to add ILO and maybe a few others to that as well)

Rochelle/Erik, please let me know if that's sufficient + then close this accordingly

**Comment by rochelleterman** [comment]
Thanks, Matt. A couple notes:

I misttyped again: What I meant to say was that Erin is not classifying ICMW as "labor" but it has the word "WORKERS" in it. 

In the program, I've linked "ICMW" to "labor". "ILO" is also linked under labor. Could you make sure that's reflected in the codebook?

```
keywords['women'] = ['CEDAW', 'eu-vaw', 'pol-women']
keywords['sex-violence'] = ['eu-vaw', 'eu-child']
keywords['children'] = ['CRC', 'eu-child']
keywords['torture'] = ['CAT']
keywords['disappearances'] = ['CPED']
keywords['disabilities'] = ['CRPD']
keywords['migrants'] = ['ICMW','eu-migrant','UNHCR']
keywords['race'] = ['ICERD']
keywords['labor'] = ['ILO', 'ICMW']
keywords['trafficking'] = ['traffick', 'eu-traff']
keywords['indigenous'] = ['ind169','un-indig']
keywords['domest-movement'] = ['kampala']
keywords['ethnic'] = ['frame-minorities']
keywords['education'] = ['unesco-ed']
keywords['culture'] = ['unesco-expr']
keywords['post-conflict'] = ['ICC']
```

**Comment by mathisonclore** [comment]
Updated + closed
