### ISSUE TITLE
Actions -  "implement" "establish" "report"

### ISSUE THREAD

**Issue by mathisonclore** [rochelleterman/uprs#4]
**Rochelle text**
We got poor agreement on "implement", "establish", and "report". Should they be modified?

**Current keywords**

| Action | Keywords |
| --- | --- |
| implement | implement |
| establish | establish |
| report | to report; reporting; reports |

**Solution**
Modify the keywords?

**Comment by rochelleterman** [comment]
these got better in later versions of testing. closing.
